/*
 * This Java source file was auto generated by running 'gradle buildSetup --type java-library'
 * by 'tw' at '12/17/13 8:25 PM' with Gradle 1.7
 *
 * @author tw, @date 12/17/13 8:25 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
